apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-e2ql
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-e2ql
    app.kubernetes.io/part-of: e2e-python-personal
  name: devfile-sample-python-basic-e2ql
  namespace: e2e-demos-mbtw-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-sample-python-basic-e2ql
status:
  loadBalancer: {}
